### ISSUE TITLE
Week 1 checklist

### ISSUE THREAD

**Issue by albertsgarde** [A4OpS/mlops-tinystories#1]
- [x] Create a git repository
 - [x] #19 Make sure that all team members have write access to the github repository
 - [x] Create a dedicated environment for you project to keep track of your packages
 - [x] Create the initial file structure using cookiecutter
 - [x] #12 Fill out the make_dataset.py file such that it downloads whatever data you need and
 - [x] #14 Add a model file and a training script and get that running
 - [x] Remember to fill out the requirements.txt file with whatever dependencies that you are using
 - [x] Remember to comply with good coding practices (pep8) while doing the project
 - [x] Do a bit of code typing and remember to document essential parts of your code
 - [x] Setup version control for your data or part of your data
 - [x] #15 Construct one or multiple docker files for your code
 - [x] #15 Build the docker files locally and make sure they work as intended
 - [x] #16 Write one or multiple configurations files for your experiments
 - [x] #16 Used Hydra to load the configurations and manage your hyperparameters
 - [x] #17 When you have something that works somewhat, remember at some point to do some profiling and see if you can optimize your code
 - [x] #18  Use Weights & Biases to log training progress and other important metrics/artifacts in your code. Additionally, consider running a hyperparameter optimization sweep.
 - [x] Use Pytorch-lightning (if applicable) to reduce the amount of boilerplate in your code
