### ISSUE TITLE
Week 2 checklist

### ISSUE THREAD

**Issue by albertsgarde** [A4OpS/mlops-tinystories#2]
- [ ] Write unit tests related to the data part of your code
 - [ ] Write unit tests related to model construction and or model training
 - [ ] Calculate the coverage.
 - [ ] Get some continuous integration running on the github repository
 - [ ] Create a data storage in GCP Bucket for you data and preferable link this with your data version control setup
 - [ ] Create a trigger workflow for automatically building your docker images
 - [ ] Get your model training in GCP using either the Engine or Vertex AI
 - [ ] Create a FastAPI application that can do inference using your model
 - [ ] If applicable, consider deploying the model locally using torchserve
 - [ ] Deploy your model in GCP using either Functions or Run as the backend
