### ISSUE TITLE
Week 3 checklist

### ISSUE THREAD

**Issue by albertsgarde** [A4OpS/mlops-tinystories#3]
- [ ] Check how robust your model is towards data drifting
 - [ ] Setup monitoring for the system telemetry of your deployed model
 - [ ] Setup monitoring for the performance of your deployed model
 - [ ] If applicable, play around with distributed data loading
 - [ ] If applicable, play around with distributed model training
 - [ ] Play around with quantization, compilation and pruning for you trained models to increase inference speed
