### ISSUE TITLE
Additional checklist

### ISSUE THREAD

**Issue by albertsgarde** [A4OpS/mlops-tinystories#4]
- [ ] Revisit your initial project description. Did the project turn out as you wanted?
 - [ ] Make sure all group members have a understanding about all parts of the project
 - [ ] Uploaded all your code to github
